# Goal definition (客户端发送的目标，例如方向和时间)
int32 left_boxID
int32 left_rbtID
float64[] left_joints

int32 right_boxID
int32 right_rbtID
float64[] right_joints

---
# Result definition (最终结果)
int64 code
string message

---
# Feedback definition (持续反馈)
int64 code
string message
